# Zuordnung Lehramt (numerische Codes -> Kürzel)
LEHRAEMTER = {
    0: "kein Eintrag",
    1: "unbekannt",
    2: "unbekannt",
    3: "unbekannt",
    4: "G",
    5: "unbekannt",
    6: "unbekannt",
    7: "unbekannt",
    8: "SF",
    9: "SF",
    10: "unbekannt",
    11: "unbekannt",
    12: "unbekannt",
    13: "unbekannt",
    14: "SF",
    15: "G",
    16: "HRSGe",
    17: "HRSGe",
    18: "HRSGe",
    19: "unbekannt",
    20: "unbekannt",
    21: "unbekannt",
    22: "unbekannt",
    23: "unbekannt",
    24: "GyGe",
    25: "unbekannt",
    26: "unbekannt",
    27: "GyGe",
    28: "unbekannt",
    29: "unbekannt",
    30: "unbekannt",
    31: "unbekannt",
    32: "unbekannt",
    33: "unbekannt",
    34: "unbekannt",
    35: "BK",
}

# Lehramtgruppe
LEHRAMTGRUPPEN = {
    1: "G",
    2: "HRSGe",
    3: "SF",
    4: "BK",
    5: "GyGe",
}
